version: "2.2"

services:
  blockchain:
    container_name: blockchain
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    environment:
      - NODE_ID=18
      - WALLET_URL=http://wallets:5000/v1
      - GENESIS_DATA="g3n3s1sbl0c4"
      - PORT=5000